### ISSUE TITLE
[BUG] OOB for Mbed OS 6.0 - error with Online Compiler

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-example-pelion#134]
**Overview**

As part of OOB and prep for Mbed 6 release, we're testing the Mbed Online Compiler (specific staging server for OOB).

**Describe the bug**

Getting a specific error at link time.

**To Reproduce**

1. Import the https://github.com/ARMmbed/mbed-os-example-pelion into the Online compiler for OOB (ide-oob ...)
2. Update Mbed OS to Mbed OS 6.0-RC2
3. Configure Pelion DM credentials
4. Select K64F
5. Compile

**Expected behavior**

A binary should be generated by the Online Compiler and downloaded to let us program the board.

**Logs**

```
Error: L6218E: Undefined symbol MBED_CLOUD_DEV_BOOTSTRAP_DEVICE_CERTIFICATE (referred from ../../build/mbed-cloud-client/factory-configurator-client/factory-configurator-client/source/fcc_dev_flow.K64F.o).
Info: Unable to download. Fix the reported errors...
```

**Device information:**
 - K64F
 - Mbed OS 6.0.0-RC2 tag (pre-release)
 - Client version: 4.4.0

**Additional context**

Note the application compiles/links ok when using Mbed CLI.

This is something for the Tools/Online compiler team to investigate

**Comment by Patater** [comment]
@MarceloSalazar Could you please provide some more detail on what steps you followed for "3. Configure Pelion DM credentials"? Also, if you are following any instructions on how to do that, could you please link? I didn't see anything in the README for this example and we should try to rectify that by linking to some instructions for how to set up the credentials for this example.

Thanks!

**Comment by MarceloSalazar** [comment]
@Patater the actual instructions are here: https://www.pelion.com/guides/connect-device-to-pelion/

- Skip to 2.3 and import the URL for this example: https://github.com/ARMmbed/mbed-os-example-pelion
- Update Mbed OS to Mbed OS 6.0-RC2 (only visible in the OOB compiler)
- Configure Pelion DM credentials - described in 3.2 here https://www.pelion.com/guides/connect-device-to-pelion/3/?board=FRDM-K64F

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTPART-9172*

**Comment by MarceloSalazar** [comment]
After investigations with @rwalton-arm concluded that the problem is neither in Mbed OS nor tools, but rather an issue with the OOB online compiler (not production): the developer credentials were not automatically fetched from Pelion DM. However, adding the credentials manually solves the problem and the application works ok on K64F.

Therefore closing this issue as don't expect to be a problem after the release.
