### ISSUE TITLE
Issue in download certificate from pelion portal 

### ISSUE THREAD

**Issue by krunalchauhan637** [ARMmbed/mbed-os-example-pelion#165]
I have download developer certificate throught last month.
But Today itself I found one strange behavior that 
when I download developer certficate It is download mbed_cloud_dev_credentials.c
but in file only "undefine" string is there.
Even I create new developer certificate also Facing same Issue
![Capture](https://user-images.githubusercontent.com/59273222/141459794-06a4c6ff-5649-40cc-bfc8-658b8cc6c435.PNG)

**Comment by krunalchauhan637** [comment]
What should I do to recover certificate ???

**Comment by teetak01** [comment]
Hi @krunalchauhan637

I have raised this issue internally. For Pelion service-related issues it is better to use https://support.pelion.com/support/login and I would recommend you to follow through that.

**Comment by mayank-arm** [comment]
@krunalchauhan637 we have addressed the issue and it should now be fixed. You may try and test now please.

**Comment by krunalchauhan637** [comment]
HI
Thank You @teetak01 @mayank-arm  for quick reply and resolution.

**Comment by krunalchauhan637** [comment]
> @krunalchauhan637 we have addressed the issue and it should now be fixed. You may try and test now please.

Yes It is working fine Now
