### ISSUE TITLE
Target Agora SIM identity

### ISSUE THREAD

**Issue by 40Grit** [ARMmbed/mbed-os-example-pelion#58]
At some point we are going to be including bootstrapping creds on the SIMs we ship with Agora kits.

Any thoughts on how we might integrate support for that for this example?

Or should it just have it's own example?

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTCLT-3852*

**Comment by MarceloSalazar** [comment]
@40Grit that's a nice feature, but probably should be included as part of Mbed OS and make it available in the configuration but it shouldn't require changes in the example app.
Anyway, that will take some time.

In the meantime, if you have a solution available that may require customization of the example app, I'd suggest you introduce it in your own example.
