### ISSUE TITLE
Use Mbed OS built in command line versus application level implementation

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/mbed-os-example-pelion#81]
This example would be more extendable and also drive development of mbed-client-cli if the standard command line interface provided with mbed-os were used.

@trowbridgec

**Comment by trowbridgec** [comment]
It might be nice to change the this example to use the built-in [`mbed-client-cli`](https://github.com/ARMmbed/mbed-os/tree/master/features/frameworks/mbed-client-cli) library which exposes a very useful command line UI. Also, it allows you to specify exact commands and requires the user to press `ENTER` before interpreting a command. In my opinion, this would allow for a better user experience by only executing commands when the user explicitly wants to, provides built-in command help info, and shows off another great Mbed tool, albeit at the expense of a slightly more complicated example application.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTPART-8958*

**Comment by loverdeg-ep** [comment]
@maclobdell

**Comment by JanneKiiskila** [comment]
@MarceloSalazar  - any opinions? The problem here is that we've been criticized very heavily for having a too complicated application as is. So, I do understand both points but fulfilling both in one app - seems a task near impossible.

**Comment by MarceloSalazar** [comment]
I believe this application is intended for intro level users, mainly coming from the [Pelion Quick Start](https://cloud.mbed.com/quick-start) and it's expected to be very basic with minimal functionality across all Pelion Ready platforms. We expect them to play and extend it if they want.
The users are not expected to use the serial terminal unless something goes wrong (typically networking problems or wrong Pelion credentials).
Therefore I don't think is appropriate to extend the CLI interface beyond what's already available.

**Comment by loverdeg-ep** [comment]
My thought is that it would provide an experience more consistent with a normal command line and make the example more easily extendable for those who want to extend it.

Obviously flash/RAM resource consumption is a top priority for this example; but if it fits?

**Comment by JanneKiiskila** [comment]
CLI interface will most likely almost never be used with anything that's an real IoT device. Those devices would work most of the time autonomously and they will not have an interface/UI which via you could even drive the CLI. The CLI would also be a security risk. The CLI we have in Mbed OS is mostly for test purposes, so from my point of view - the CLI adds value for sure, but it's not the mbed-os-example-pelion anymore, it is actually then a new application (mbed-os-example-pelion-testapp or similar).

**Comment by MarceloSalazar** [comment]
Closing as it's not considered appropriate for this example application.
